version: "3"

services:
  apache:
    image: docker.ub.gu.se/gub-apache2:release-2020.12.001
    restart: always
    network_mode: "host"
    volumes:
      - "/opt/gub-apache2/sites:/etc/apache2/sites-enabled"
      - "/opt/gub-apache2/conf:/etc/apache2/conf-enabled"
      - "/opt/gub-apache2/logs:/var/log/apache2"
      - "/opt/gub-apache2/ssl:/etc/ssl/apache2"
      - "/opt/gub-apache2/data:/data"
      - "/opt/gub-apache2/webroot:/var/www/html"
      - "/etc/letsencrypt/live:/etc/letsencrypt/live"
